language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
# command to run tests
install:
  - pip install -r requirements.txt
script:
  - pytest